# Generated by Django 4.0.4 on 2022-04-25 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCaoDoanhSo',
            fields=[
                ('MaBaoCaoDoanhSo', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
                ('TongDoanhSo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaiLy',
            fields=[
                ('MaDaiLy', models.AutoField(primary_key=True, serialize=False)),
                ('TenDaiLy', models.CharField(max_length=50)),
                ('DiaChi', models.CharField(max_length=50)),
                ('DienThoai', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('SoTienNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DVT',
            fields=[
                ('MaDVT', models.AutoField(primary_key=True, serialize=False)),
                ('TenDVT', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiDaiLy',
            fields=[
                ('MaLoaiDaiLy', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoaiDaiLy', models.CharField(max_length=50)),
                ('SoNoToiDa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('MaNCC', models.AutoField(primary_key=True, serialize=False)),
                ('TenNCC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quan',
            fields=[
                ('MaQuan', models.AutoField(primary_key=True, serialize=False)),
                ('TenQuan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThamSo',
            fields=[
                ('MaThamSo', models.AutoField(primary_key=True, serialize=False)),
                ('TenThamSo', models.CharField(max_length=50)),
                ('GiaTri', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXuatHang',
            fields=[
                ('MaPhieuXuatHang', models.AutoField(primary_key=True, serialize=False)),
                ('NgayXuat', models.DateField()),
                ('TongTien', models.IntegerField()),
                ('MaDaiLy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.daily')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuThuTien',
            fields=[
                ('MaPhieuThuTien', models.AutoField(primary_key=True, serialize=False)),
                ('NgayThuTien', models.DateField()),
                ('SoTienThu', models.IntegerField()),
                ('MaDaiLy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.daily')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapHang',
            fields=[
                ('MaPhieuNhapHang', models.AutoField(primary_key=True, serialize=False)),
                ('NgayNhap', models.DateField()),
                ('TongTien', models.IntegerField()),
                ('MaNCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('MaMatHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenMatHang', models.CharField(max_length=100)),
                ('SoLuongTon', models.IntegerField()),
                ('DVT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.dvt')),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='MaLoaiDaiLy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.loaidaily'),
        ),
        migrations.AddField(
            model_name='daily',
            name='MaQuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.quan'),
        ),
        migrations.CreateModel(
            name='ChiTietPhieuXuatHang',
            fields=[
                ('MaChiTietPhieuXuatHang', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('DonGia', models.IntegerField()),
                ('ThanhTien', models.IntegerField()),
                ('MaMatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.mathang')),
                ('MaPhieuXuatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.phieuxuathang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhapHang',
            fields=[
                ('MaChiTietPhieuNhapHang', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField()),
                ('DonGia', models.IntegerField()),
                ('ThanhTien', models.IntegerField()),
                ('MaMatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.mathang')),
                ('MaPhieuNhapHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.phieunhaphang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietBaoCaoDoanhSo',
            fields=[
                ('MaChiTietBaoCaoDoanhSo', models.AutoField(primary_key=True, serialize=False)),
                ('SoPhieuXuat', models.IntegerField()),
                ('TongGiaTri', models.IntegerField()),
                ('TiLe', models.FloatField()),
                ('MaBaoCaoDoanhSo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.baocaodoanhso')),
                ('MaDaiLy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.daily')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCaoCongNo',
            fields=[
                ('MaBaoCaoCongNo', models.AutoField(primary_key=True, serialize=False)),
                ('Thang', models.IntegerField()),
                ('Nam', models.IntegerField()),
                ('NoDau', models.IntegerField()),
                ('NoCuoi', models.IntegerField()),
                ('PhatSinh', models.IntegerField()),
                ('TongCongNo', models.IntegerField()),
                ('MaDaiLy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapi.daily')),
            ],
        ),
    ]
