# Generated by Django 4.0.3 on 2022-06-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='NgayTiepNhan',
            field=models.DateField(default='2022-06-01'),
        ),
    ]
