# Generated by Django 4.0.3 on 2022-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0002_daily_ngaytiepnhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='SoTienNo',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
