# Generated by Django 4.0.4 on 2022-06-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0002_alter_thamso_giatri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baocaocongno',
            name='TongCongNo',
        ),
    ]
