# Generated by Django 4.0.3 on 2022-06-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0003_alter_daily_email_alter_daily_sotienno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='SoTienNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
