# Generated by Django 4.0.4 on 2022-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0003_remove_baocaocongno_tongcongno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='SoTienNo',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
