# Generated by Django 4.0.3 on 2022-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapi', '0004_alter_daily_sotienno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphieuxuathang',
            name='DonGia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitietphieuxuathang',
            name='SoLuong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chitietphieuxuathang',
            name='ThanhTien',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phieuxuathang',
            name='NgayXuat',
            field=models.DateField(default='06-06-2022'),
        ),
        migrations.AlterField(
            model_name='phieuxuathang',
            name='TongTien',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
